version: '3.8'

services:
  web:
    build: .
    command: gunicorn image_generator.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - celery

  celery:
    build: .
    command: celery -A image_generator worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6380"
